name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

env:
  VERSION_NAME: ''
  VERSION_CODE: ''
  APK_PATH: app/build/outputs/apk/
  BUNDLE_PATH: app/build/outputs/bundle/

jobs:
  bump-version:
    name: Bump version
    runs-on: ubuntu-latest

    outputs:
      version_name: ${{ steps.versions.outputs.version_name }}
      version_code: ${{ steps.versions.outputs.version_code }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.repository.default_branch }}
          fetch-depth: 0

      - name: Extract existing version code
        id: versions
        run: |
          # Extract version number from branch name
          tag=${{ github.ref_name }}
          version_name=${tag:1}

          # Get existing version code from build.gradle
          version_code=$(grep 'versionCode' app/build.gradle.kts | grep -o '[0-9]*')

          # Increment existing version code by 1
          version_code=$((version_code + 1))

          # Set environment variable for later use
          echo "VERSION_NAME=$version_name" >> $GITHUB_ENV
          echo "VERSION_CODE=$version_code" >> $GITHUB_ENV

          # Set output for step
          echo "version_name=$version_name" >> $GITHUB_OUTPUT
          echo "version_code=$version_code" >> $GITHUB_OUTPUT

      - name: Increase version code and change version name
        run: |
          # Update build.gradle with new version code and name
          sed -i 's/versionCode = [0-9]*/versionCode = ${{ env.VERSION_CODE }}/' app/build.gradle.kts
          sed -i 's/versionName = "[^"]*"/versionName = "${{ env.VERSION_NAME }}"/' app/build.gradle.kts

      - name: Commit changes
        uses: gentslava/commit@v2.0.0
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: app/build.gradle.kts
          commit-message: Bump version code and change version name to ${{ env.VERSION_CODE }}-${{ env.VERSION_NAME }}
          ref: ${{ github.event.repository.default_branch }}

  build:
    strategy:
      matrix:
        flavor: [ github, googleplay, amazon ]

    name: Build APK
    needs: bump-version
    runs-on: ubuntu-latest

    env:
      VERSION_NAME: ${{ needs.bump-version.outputs.version_name }}
      VERSION_CODE: ${{ needs.bump-version.outputs.version_code }}

    steps:
    - id: flavorString
      uses: ASzc/change-string-case-action@v6
      with:
        string: ${{ matrix.flavor }}

    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.repository.default_branch }}
        fetch-depth: 0

    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Checkout keystore repo
      uses: actions/checkout@v4
      with:
        repository: ${{ secrets.KEYSTORE_GIT_REPOSITORY }}
        token: ${{ secrets.KEYSTORE_ACCESS_TOKEN }}
        path: app/keystore

    - name: Prepare signing properties
      run: |
        mkdir signing && touch signing/release.properties
        echo "storeFile=${{ secrets.KEYSTORE_FILE }}" >> signing/release.properties
        echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> signing/release.properties
        echo "keyAlias=${{ secrets.RELEASE_SIGN_KEY_ALIAS }}" >> signing/release.properties
        echo "keyPassword=${{ secrets.RELEASE_SIGN_KEY_PASSWORD }}" >> signing/release.properties

        touch signing/legacy.properties
        echo "storeFile=${{ secrets.KEYSTORE_FILE }}" >> signing/legacy.properties
        echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> signing/legacy.properties
        echo "keyAlias=${{ secrets.RELEASE_SIGN_KEY_ALIAS }}" >> signing/legacy.properties
        echo "keyPassword=${{ secrets.RELEASE_SIGN_KEY_PASSWORD }}" >> signing/legacy.properties

    - name: Run ${{ steps.flavorString.outputs.capitalized }} Build
      if: matrix.flavor == 'github'
      run: ./gradlew assemble${{ steps.flavorString.outputs.capitalized }}Release --stacktrace

    - name: Run ${{ steps.flavorString.outputs.capitalized }} Build
      if: matrix.flavor != 'github'
      run: ./gradlew bundle${{ steps.flavorString.outputs.capitalized }}Release

    - name: Upload ${{ steps.flavorString.outputs.capitalized }} Release APK
      if: matrix.flavor == 'github'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.flavor }}-release.apk
        path: ${{ env.APK_PATH }}${{ matrix.flavor }}/release/app-${{ matrix.flavor }}-release.apk

    - name: Upload ${{ steps.flavorString.outputs.capitalized }} Bundle
      if: matrix.flavor != 'github'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.flavor }}-release.aab
        path: ${{ env.BUNDLE_PATH }}${{ matrix.flavor }}Release/app-${{ matrix.flavor }}-release.aab

    - name: Upload ${{ steps.flavorString.outputs.capitalized }} apk to GH release
      if: matrix.flavor == 'github'
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        file: ${{ env.APK_PATH }}${{ matrix.flavor }}/release/app-${{ matrix.flavor }}-release.apk
        asset_name: aerial-views-${{ env.VERSION_NAME }}.apk